global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alert-manager-0-28:9093

# Rule files
rule_files:
  - /opt/bitnami/prometheus/conf/rules.yaml 
  - /opt/bitnami/prometheus/conf/alerts.yaml

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets:
          - 10.0.13.32:9100     # engine-master
          - 10.0.142.29:9100    # k8s-worker-node-0
          - 10.0.137.181:9100   # k8s-worker-node-1
    relabel_configs:
      - source_labels: [__address__]
        regex: 10.0.13.32:9100
        target_label: nodename
        replacement: engine-master
      - source_labels: [__address__]
        regex: 10.0.142.29:9100
        target_label: nodename
        replacement: k8s-worker-node-0
      - source_labels: [__address__]
        regex: 10.0.137.181:9100
        target_label: nodename
        replacement: k8s-worker-node-1

  - job_name: 'kube-state-metrics'
    static_configs:
      - targets: ['kube-state-metrics.kube-system.svc.cluster.local:8080']
