# Global configuration
global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Scrape configurations
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'windows_server'
    metrics_path: /metrics
    static_configs:
      - targets: ['65.2.168.89:9182']
        labels:
          instance: 'windows-server'
